config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :links, :only => [:new, :create, :destroy]
  end
  resources :links, :only => [:index, :show] do
    resources :votes, :only => [:create, :destroy]
    resources :comments, :except => :show
  end
  resources :comments do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :comment, presence: true

  belongs_to :link
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/link.rb
class Link < ActiveRecord::Base

  validates :title, presence: true
  validates :user_id, presence: true
  validates :url, presence: true
  belongs_to :user
  has_many :votes
  has_many :comments, as: :commentable

  def vote_count
    votes.count
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :name, :presence => true, uniqueness: true
  has_many :links
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  validates :link_id, presence: true
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :find_params

  def index
    @comments = @commentable.comments
  end

  def new
    # @link = Link.find(params[:link_id])
    @comment = @commentable.comments.new
  end

  def create
    if params[:link_id]
      @commentable = Link.find(params[:link_id])
    elsif params[:comment_id]
      @commentable = Comment.find(params[:comment_id])
    end
    @comment = @commentable.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "You have commented!"
      if @comment.commentable_type == 'Link'
        redirect_to link_path(@comment.commentable_id)
      else
        redirect_to link_path(@commentable.commentable_id)
      end
    else
      render 'new'
    end
  end

  def edit
    @link = Link.find(params[:link_id])
    @comment = @link.comments.find(params[:id])
  end

  def update
    @link = Link.find(params[:link_id])
    @comment = @link.comments.find(params[:id])
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated!'
      redirect_to link_comments_path
    else
      flash[:notice] = 'Update Comment Error'
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Comment deleted!'
    redirect_to link_comments_path
  end

private

  def comment_params
    params.require(:comment).permit(:link_id, :comment)
  end

  def find_params
    resource, id = request.path.split('/')[1,2]
    @commentable = resource.singularize.classify.constantize.find(id)
    # poly_class = [Link, Comment].detect { |type| params["#{type.name.underscore}_id"]}
    # @commentable = poly_class.find(params["#{poly_class.name.underscore}_id"])
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @user = User.find(params[:user_id])
    @link = @user.links.new(link_params)
    if @link.save
      flash[:notice] = "New link has been created!"
    else
      render 'new'
    end
  end

private
  def link_params
    params.require(:link).permit(:user_id, :title, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'New user name created!'
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'User Name updated!'
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'User has been deleted from system!'
    redirect_to users_path
  end
private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @link = Link.find(params[:link_id])
    @vote = @link.votes.create
    if @vote.save
      flash[:notice] = "You have upvoted on this Link!"
      redirect_to links_path
    else
      flash[:alert] = "Ability to vote DISABLED!"
    end
  end



# private
#   def vote_params
#     params.require(:vote).permit(:user_id, :link_id)
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<% if @commentable_type == 'Link' %>
  <%= form_for [@link, @comment] do |f| %>
  <input type='hidden' name='commentable_type' value='Link'>
    <div class='form-group'>
      <%= f.label :comment %>
    </div>
    <div class='form-group'>
      <%= f.text_area :comment, size: "100x10" %>
    </div>
    <%= button_to 'Submit', link_comments_path(@link), :class => 'btn btn-success' %>
  <% end %>

<% else @commentable_type == 'Comment' %>
  <%= form_for [@commentable, @comment] do |f| %>
  <input type='hidden' name='commentable_type' value='Comment'>
    <div class='form-group'>
      <%= f.label :comment %>
    </div>
    <div class='form-group'>
      <%= f.text_area :comment, size: "100x10" %>
    </div>
    <%= button_to 'Submit', comment_comments_path(@commentable), :class => 'btn btn-success' %>
  <% end %>

<% end %>

app/views/comments/edit.html.erb
<% content_for(:title, 'Edit Comment | hacker') %>

<%= render('layouts/errors', object: @comment) %>

<%= render 'form' %>

app/views/comments/index.html.erb
<% content_for(:title, 'Comments | Hacker') %>

<h1><a href="<%= @link.url %>"><%= @link.title %></a></h1>
<p>Submitted by: <a href="/users/<%= @link.user.id %>"><%= @link.user.name %></a></p>

<h3>Comments</h3>

<% @comments.each do |comment| %>
  <p><%= comment.comment %></p>
     <%= link_to 'Edit', edit_link_comment_path(comment.link, comment), :class => 'btn btn-info' %>
    <%= link_to  'Delete', link_comment_path(@link, comment), :data => {
                          :confirm => 'Are you sure you want to delete this comment',
                          :method => 'delete' },
                          :class => 'btn btn-danger' %>
<%end %>

app/views/comments/new.html.erb
<% content_for(:title, 'New Comment | Hacker') %>

<%= render('layouts/errors', object: @comment) %>

<%= render('form') %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3><span class='label label-danger'><%= flash[:alert] %></span></h3>
<h3><span class='label label-success'><%= flash[:notice] %></span></h3>
<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for [:user, @link] do |f| %>
  <div class='form-group'>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <%= f.submit(:class => 'btn btn-success') %>
  </div>
<% end %>

app/views/links/index.html.erb
<% content_for(:title, "Links | Hacker") %>

<h1>Links</h1>

<% @links.sort_by(&:vote_count).reverse.each do |link| %>
  <p><%= link.votes.count %></p>
  <p><a href="<%= link.url %>"><%= link.title %></a></p>
  <p>Submitted by: <a href="/users/<%= link.user.id %>"><%= link.user.name %></a></p>
  <%= button_to 'Upvote', link_votes_path(link) %>
  <%= link_to 'Comment', new_link_comment_path(link), class: 'btn btn-success' %>
<% end %>

app/views/links/new.html.erb
<% content_for(:title, "New | Hacker") %>

<h1>Add A New Link</h1>

<%= render('layouts/errors', :object => @link) %>

<%= render 'form' %>

app/views/links/show.html.erb
<% content_for(:title, "Show | Hacker") %>

<h1><a href="<%= @link.url %>"><%= @link.title %></a></h1>
<p>Submitted by <a href="/users/<%= @link.user.id %>"><%= @link.user.name %></a></p>

<% @link.comments.each do |comment| %>
  <p><%= comment.comment %></p>
  <%= link_to 'Comment on this', new_comment_comment_path(comment), :class => 'btn btn-success' %>
  <% comment.comments.each do |nested| %>
    <p><%= nested.comment %><p>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => 'btn btn-success') %>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "Edit | Hacker") %>

<h1>Edit User</h1>

<%= render('layouts/errors', :object => @user) %>

<%= render('form') %>

<p><%= link_to 'Delete', user_path(@user),
                      :data => { :confirm => 'Are you sure you want to delete this?',
                      :method => 'delete'},
                      :class => 'btn btn-danger' %>
</p>

app/views/users/index.html.erb
<% content_for(:title, "Home | Hacker") %>

<h1>Homepage</h1>

app/views/users/new.html.erb
<% content_for(:title, "New User | Hacker") %>

<h1>Create a new username</h1>

<%= render('layouts/errors', :object => @user) %>
<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, 'User | Hacker') %>

<h1><%= @user.name %></h1>

<% @user.links.each do |link| %>
<p><a href="<%= link.url %>"><%= link.title %></a></p>
<% end %>

<a href="/users/<%= @user.id %>/links/new" class='btn btn-success'>Create a new Link!</a>